/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BUNDLE "ifd-ccid.bundle"

#undef ENABLE_ZLP

#define HAVE_STRLCAT

#define HAVE_STRLCPY

#undef NO_LOG

#undef USE_COMPOSITE_AS_MULTISLOT

#undef USE_OS_LOG

#define VERSION "1.6.1"

