/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef MBIM_QMUX_ENABLED

#define MM_RUNTIME_CHECK_ENABLED

#define PACKAGE_VERSION "1.38.0"

#undef QMI_GROUPNAME_ENABLED

#define QMI_QRTR_SUPPORTED 1

#undef QMI_USERNAME_ENABLED

#define RMNET_SUPPORT_ENABLED

#undef WITH_UDEV

