#!/system/bin/sh
Font_color_suffix="\033[0m"
Red_font_prefix="\033[31m" && Red_background_prefix="\033[41;37m"         #红
Green_font_prefix="\033[32m" && Green_background_prefix="\033[42;37m"     #绿
Yellow_font_prefix="\033[33m" && Yellow_background_prefix="\033[43;37m"   #黄
Blue_font_prefix="\033[36m" && Blue_background_prefix="\033[44;37m"       #蓝
Magenta_font_prefix="\033[35m" && Magenta_background_prefix="\033[45;37m" #紫

Error="${Red_font_prefix}[错误]${Font_color_suffix}"
Tip="${Red_background_prefix}[提示]${Font_color_suffix}"

Tip_EID="${Yellow_font_prefix}[EID]${Font_color_suffix}"
Tip_FREE="${Yellow_font_prefix}[可用空间]${Font_color_suffix}"

Info_LPAC="${Green_font_prefix}[LPAC]${Font_color_suffix}"
Info_ESIM="${Green_font_prefix}[eSIM]${Font_color_suffix}"
Info_ICCID="${Green_font_prefix}[ICCID]${Font_color_suffix}"
Info_SPN="${Green_font_prefix}[提供商]${Font_color_suffix}"

Info_DL="${Green_font_prefix}[下载成功]${Font_color_suffix}"
Info_SW="${Green_font_prefix}[切换成功]${Font_color_suffix}"
Info_DE="${Green_font_prefix}[删除成功]${Font_color_suffix}"

Error_LPAC="${Red_font_prefix}[LPAC]${Font_color_suffix}"
Error_DL="${Red_font_prefix}[下载失败]${Font_color_suffix}"
Error_SW="${Red_font_prefix}[切换失败]${Font_color_suffix}"
Error_DE="${Red_font_prefix}[删除失败]${Font_color_suffix}"


ESIM_INIT="null"
ESIM_EID="null"
ESIM_FREE="null"
ESIM_NAME="null"
ESIM_ICCID="null"

lpac_chip_info() {
  if [ $ESIM_INIT != 1 ]; then
    LPAC_LOG=`lpac-hw chip info`
    if echo "$LPAC_LOG" | grep -q "eidValue"; then
      ESIM_INIT=1
      ESIM_EID=`echo "$LPAC_LOG" | jq .payload.data.eidValue`
      ESIM_FREE=`echo "$LPAC_LOG" | jq .payload.data.EUICCInfo2.extCardResource.freeNonVolatileMemory`
      lpac_profile_get_enable
    fi
  fi
}

lpac_profile_get_enable() {
  LPAC_LOG=`lpac-hw profile list`
  if echo "$LPAC_LOG" | grep -q "data"; then
    LPAC_JSON_TMP=`echo "$LPAC_LOG" | jq .payload.data`
    TMPL=`echo "$LPAC_JSON_TMP" | jq length`
    #
    for i in $(seq 1 $TMPL)
    do
       NUM=$(($i - 1))
       LPAC_CACHE_INFO=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileState`
       if [[ $LPAC_CACHE_INFO == '"enabled"' ]]; then
         ESIM_NAME=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileNickname`
         ESIM_ICCID=`echo "$LPAC_JSON_TMP" | jq .[$NUM].iccid`
         if [[ $ESIM_NAME == "null" ]]; then
           ESIM_NAME=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileName`
         fi
       fi
    done
    #
  fi
}

lpac_profile_download() {
echo -e "请输入LPA代码? [格式为：LPA:1\$AAA\$BBB\$CCC]:"
read lpa_code
[ -z "${lpa_code}" ] && echo "你还没有输入LPA代码，请重新输入" && lpac_profile_download
  LPA=`echo $lpa_code | sed 's/\"//g' | sed "s/'//g"`

echo -e "是否需要手动确认下载? [y/N] :"
read yn
  [ -z "${yn}" ] && yn="n"
  if [[ $yn == [Yy] ]]; then
    lpac-hw profile download -p -a $LPA
  else
    LPAC_LOG=`echo y | lpac-hw profile download -p -a $LPA`
    LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
    LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
    if [[ $LOG_LV != 0 ]]; then
      LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
      echo -e "${Error_DL} $LOG_ER"
    else
      LOG_ER=`echo "$LPAC_LOG" | grep 'iccid":"' | jq .payload.data.iccid`
      echo -e "${Info_DL} $LOG_ER"
    fi
  fi

ESIM_INIT=2
echo -e "是否还需要下载eSIM? [Y/n] :"
read yn
  [ -z "${yn}" ] && yn="y"
  if [[ $yn == [Yy] ]]; then
    lpac_profile_download
  else
    lpac_menu
  fi
}

lpac_profile_list() {
  LPAC_LOG=`lpac-hw profile list`
  if echo "$LPAC_LOG" | grep -q "data"; then
    LPAC_JSON_TMP=`echo "$LPAC_LOG" | jq .payload.data`
    TMPL=`echo "$LPAC_JSON_TMP" | jq length`
    #
    for i in $(seq 1 $TMPL)
    do
      NUM=$(($i - 1))
      LPAC_CACHE_INFO=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileState`
      ESIM_NAME_TMP=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileNickname`
      ESIM_ICCID_TMP=`echo "$LPAC_JSON_TMP" | jq .[$NUM].iccid`
      ESIM_SPN_TMP=`echo "$LPAC_JSON_TMP" | jq .[$NUM].serviceProviderName`
      if [[ $ESIM_NAME_TMP == "null" ]]; then
        ESIM_NAME_TMP=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileName`
      fi
      if [[ $LPAC_CACHE_INFO == '"enabled"' ]]; then
         echo -e "${Red_background_prefix}—————— $NUM ——————${Font_color_suffix}"
         echo -e "${Info_ESIM}: ${Blue_background_prefix}$ESIM_NAME_TMP${Font_color_suffix}"
         echo -e "${Info_SPN}: ${Blue_background_prefix}$ESIM_SPN_TMP${Font_color_suffix}"
         echo -e "${Info_ICCID}: ${Blue_background_prefix}$ESIM_ICCID_TMP${Font_color_suffix}"
      else
         echo -e "—————— $NUM ——————"
         echo -e "${Info_ESIM}: $ESIM_NAME_TMP"
         echo -e "${Info_SPN}: $ESIM_SPN_TMP"
         echo -e "${Info_ICCID}: $ESIM_ICCID_TMP"
      fi
    done
    #
    echo -e "————————————"
  else
    echo -e "$Error eSIM读取失败"
  fi
}

lpac_profile_switch() {
  lpac_profile_list
  echo -e "请输入切换卡的ICCID\n如需取消操作请输 [n]:"
  read iccid
  [ -z "${iccid}" ] && iccid="n"
  if [[ $iccid == [Nn] ]]; then
    lpac_menu && exit 1
  fi

  ICCID_NUM=`echo $iccid | sed 's/\"//g' | sed "s/'//g"`
  LPAC_LOG=`lpac-hw profile enable $ICCID_NUM`
  LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
  LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
  if [[ $LOG_LV != 0 ]]; then
    LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
    echo -e "${Error_SW} $LOG_ER"
  else
    sleep 6
    ESIM_INIT=2
    echo -e "${Info_SW}"
  fi
  echo -e "$Tip 需要重载SIM卡方可生效。如出现长时间无信号，请尝试${Blue_background_prefix}[插拔SIM卡]${Font_color_suffix}或${Blue_background_prefix}[重启手机]${Font_color_suffix}"
  lpac_kill
}

lpac_profile_delete() {
  lpac_profile_list
  echo -e "请输入删除卡的ICCID\n如需取消操作请输 [n]:"
  read iccid
  [ -z "${iccid}" ] && iccid="n"
  if [[ $iccid == [Nn] ]]; then
    lpac_menu && exit 1
  fi

  ICCID_NUM=`echo $iccid | sed 's/\"//g' | sed "s/'//g"`
  LPAC_LOG=`lpac-hw profile delete $ICCID_NUM`
  LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
  LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
  if [[ $LOG_LV != 0 ]]; then
    LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
    echo -e "${Error_DE} $LOG_ER"
  else
    sleep 6
    ESIM_INIT=2
    echo -e "${Info_DE}"
  fi
  lpac_kill
}

lpac_profile_preview() {
echo -e "请输入LPA代码? [格式为：LPA:1\$AAA\$BBB\$CCC]:"
read lpa_code
[ -z "${lpa_code}" ] && echo "你还没有输入LPA代码，请重新输入" && lpac_profile_download
  LPA=`echo $lpa_code | sed 's/\"//g' | sed "s/'//g"`
#
  LPAC_LOG=`echo n | lpac-hw profile download -p -a $LPA`
  if echo "$LPAC_LOG" | grep -q "iccid"; then
    ESIM_JSON_TMP=`echo "$LPAC_LOG" | grep 'iccid":"'`
    ESIM_NAME_TMP=`echo "$ESIM_JSON_TMP" | jq .payload.data.profileName`
    ESIM_ICCID_TMP=`echo "$ESIM_JSON_TMP" | jq .payload.data.iccid`
    ESIM_SPN_TMP=`echo "$ESIM_JSON_TMP" | jq .payload.data.serviceProviderName`
    echo -e "${Blue_background_prefix}[有效的LPA 读取到以下信息${Font_color_suffix}]"
    echo -e "${Info_ESIM}: $ESIM_NAME_TMP"
    echo -e "${Info_SPN}: $ESIM_SPN_TMP"
    echo -e "${Info_ICCID}: $ESIM_ICCID_TMP"
    echo -e "————————————"
  else
    echo -e "${Error_LPAC} 无法获取LPA信息"
  fi
#
echo -e "是否还需要继续使用? [Y/n] :"
read yn
  [ -z "${yn}" ] && yn="y"
  if [[ $yn == [Yy] ]]; then
    lpac_profile_download
  else
    lpac_menu
  fi
}

lpac_profile_nickname() {
  lpac_profile_list
  echo -e "请输入需要修改昵称的ICCID\n如需取消操作请输 [n]:"
  read iccid
  [ -z "${iccid}" ] && iccid="n"
  if [[ $iccid == [Nn] ]]; then
    lpac_menu && exit 1
  fi

  echo -e "请输入修改后的昵称:"
  read nick_name
  if [ -n "${nick_name}" ]; then
    ICCID_NUM=`echo $iccid | sed 's/\"//g' | sed "s/'//g"`
    NEW_NAME=`echo $nick_name | sed 's/\"//g' | sed "s/'//g" | sed 's/\ /\_/g'`
    LPAC_LOG=`lpac-hw profile nickname $ICCID_NUM ${NEW_NAME}`
    LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
    LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
    if [[ $LOG_LV != 0 ]]; then
      LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
      echo -e "${Error_LPAC} 昵称失败: $LOG_ER"
    else
      ESIM_INIT=2
      echo -e "${Green_background_prefix}[$ICCID_NUM]:${Font_color_suffix} ${NEW_NAME}"
      echo -e "${Info_LPAC} 昵称修改成功"
    fi
    echo -e "是否还需要继续使用? [Y/n] :"
    read yn
    [ -z "${yn}" ] && yn="y"
    if [[ $yn == [Yy] ]]; then
      lpac_profile_nickname && exit 1
    else
      lpac_menu
    fi
  else
    echo -e "你没有输入昵称，已取消操作。是否需要重新操作? [Y/n] :"
    read yn
    [ -z "${yn}" ] && yn="y"
    if [[ $yn == [Yy] ]]; then
      lpac_profile_nickname && exit 1
    else
      lpac_menu
    fi
  fi
}

lpac_notification_list() {
  LPAC_LOG=`lpac-hw notification list`
  if echo "$LPAC_LOG" | grep -q "data"; then
    LPAC_JSON_TMP=`echo "$LPAC_LOG" | jq .payload.data`
    TMPL=`echo "$LPAC_JSON_TMP" | jq length`
    #
    if [[ $TMPL != 0 ]]; then
      echo -e "———————通知列表———————"
      for i in $(seq 1 $TMPL)
      do
        NUM=$(($i - 1))
        LPAC_TZ_ID=`echo "$LPAC_JSON_TMP" | jq .[$NUM].seqNumber`
        ESIM_TZ_MO=`echo "$LPAC_JSON_TMP" | jq .[$NUM].profileManagementOperation`
        ESIM_ICCID_TMP=`echo "$LPAC_JSON_TMP" | jq .[$NUM].iccid`
        LPAC_TZ_TYPE="null"
        echo -e "—————— ID: $LPAC_TZ_ID ——————"
        if [ $ESIM_TZ_MO == '"install"' ]; then
          LPAC_TZ_TYPE="${Blue_font_prefix}[已下载]${Font_color_suffix}"
        elif [ $ESIM_TZ_MO == '"disable"' ]; then
          LPAC_TZ_TYPE="${Yellow_font_prefix}[已禁用]${Font_color_suffix}"
        elif [ $ESIM_TZ_MO == '"enable"' ]; then
          LPAC_TZ_TYPE="${Green_font_prefix}[已启用]${Font_color_suffix}"
        elif [ $ESIM_TZ_MO == '"delete"' ]; then
          LPAC_TZ_TYPE="${Red_font_prefix}[已删除]${Font_color_suffix}"
        fi
        echo -e "${LPAC_TZ_TYPE}: $ESIM_ICCID_TMP"
      done
    else
      echo -e "———————没有通知———————"
    fi
    #
    echo -e "—————————————————————"
  else
    echo -e "$Error eSIM读取失败"
  fi
}

lpac_notification() {
  lpac_notification_list

echo -e "请输入通知ID进行操作
(如果输入“all”则视为删除全部通知):"
read tzid
  tzid=`echo $tzid | sed 's/\"//g' | sed "s/'//g"`
#
  if [[ $tzid == 'all' ]]; then
    LPAC_LOG=`lpac-hw notification remove -a`
    LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
    LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
    if [[ $LOG_LV != 0 ]]; then
      #LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
      echo -e "${Error_LPAC} 删除失败"
    else
      echo -e "${Info_LPAC} 已删除全部通知"
    fi
  else
    echo -e "请输入操作类型 [发送/0 | 删除/1]:"
    read tzidx
    if [[ $tzidx == 0 ]]; then
      LPAC_LOG=`lpac-hw notification process $tzid`
      LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
      LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
      if [[ $LOG_LV != 0 ]]; then
        LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
        echo -e "${Error_LPAC} 发送失败 $LOG_ER"
      else
        echo -e "${Info_LPAC} 已发送通知"
      fi
    elif [[ $tzidx == 1 ]]; then
      LPAC_LOG=`lpac-hw notification remove $tzid`
      LOG_TMP=`echo "$LPAC_LOG" | grep '"type":"lpa"'`
      LOG_LV=`echo "$LOG_TMP" | jq .payload.code`
      if [[ $LOG_LV != 0 ]]; then
        LOG_ER=`echo "$LOG_TMP" | jq .payload.data`
        echo -e "${Error_LPAC} 删除失败 $LOG_ER"
      else
        echo -e "${Info_LPAC} 已删除通知"
      fi
    else
      echo -e "${Error_LPAC} 输入错误，只能输入“0”或“1”"
    fi
  fi

echo -e "是否还需要继续使用? [Y/n] :"
read yn
  [ -z "${yn}" ] && yn="y"
  if [[ $yn == [Yy] ]]; then
    lpac_notification
  else
    lpac_menu
  fi
}

lpac_kill_info() {
  echo -e "$Tip 如出现长时间无信号、无法上网、无法拨打电话等。重载SIM卡将解决这一问题"
  lpac_kill
}
lpac_kill() {
  echo -e "是否需要重载SIM卡? [Y/n] :"
  read yn
    [ -z "${yn}" ] && yn="y"
    if [[ $yn == [Yy] ]]; then
      #echo -e "${Info_LPAC} 命令执行中..."
      #sleep 6
      #am broadcast -a android.intent.action.SIM_STATE_CHANGED
      echo -e "${Info_LPAC} 命令执行中......"
      killall com.android.phone
      echo -e "${Info_LPAC} 命令执行完毕"
    else
      lpac_menu
  fi
}

lpac_reboot() {
echo -e "$Tip 如果出现故障问题，请先执行${Blue_background_prefix}[重载SIM卡]${Font_color_suffix}并重新${Blue_background_prefix}[插拔SIM卡]${Font_color_suffix}。如果这样也无法解决故障问题，重启手机将解决这一问题"
echo -e "是否需要重启手机? [y/N] :"
read yn
  [ -z "${yn}" ] && yn="n"
  if [[ $yn == [Yy] ]]; then
    reboot
  else
    lpac_menu
  fi
}

lpac_help() {
  echo -e "
——————————————————————
lpac [chip|profile|notification] [参数]

-> chip:
     info             查看eUICC卡片信息
     defaultsmdp [..] 修改eUICC卡的SM-DP+服务器地址
     purge            格式化eUICC卡(谨慎操作！)
示例：
    【修改SM-DP+】${Blue_background_prefix}lpac chip defaultsmdp 'lpa.ds.gsma.com'${Font_color_suffix}

-> profile:
     list             查看eUICC配置文件
     nickname [iccid] [name]
                      为指定的配置文件设置别名
     enable [iccid]   启用指定配置文件
     disable [iccid]  禁用指定配置文件
     delete [iccid]   删除指定配置文件
示例：
    【设置别名】${Blue_background_prefix}lpac profile nickname '898612345678' '中国移动'${Font_color_suffix}
    【启用配置】${Blue_background_prefix}lpac profile enable '898612345678'${Font_color_suffix}

-> profile download:  下载配置
     -s               [可选]SM-DP+服务器
     -m               [可选]激活码
     -c               [可选]确认码
     -i               [可选]IMEI
     -p               [可选]交互式预览模式
     -a               LPA代码
示例：
    【下载(手动输入)】${Blue_background_prefix}lpac profile download -s rsp.esim.com -m 'QR-AB-CD-E78'${Font_color_suffix}
    【下载(LPA代码)】${Blue_background_prefix}lpac profile download -a 'LPA:1$rsp.esim.com$QR-AB-CD-E78'${Font_color_suffix}

-> profile discovery: 检测在SM-DS服务器上注册的可用配置文件
     -s               SM-DS服务器
     -i               [可选]IMEI

-> notification:
     list              查看eUICC通知列表
     process [..] [id] 发送通知
             -a        发送全部通知
             -r        自动删除已发送的通知
     remove [..] [id]  删除通知
             -a        删除所有通知
示例：
    【发送指定通知】${Blue_background_prefix}lpac notification process '11'${Font_color_suffix}
    【删除所有通知】${Blue_background_prefix}lpac notification remove -a${Font_color_suffix}

——————————————————————
lpac [a|k|h]

-> a:    简易操作界面

-> k:    重载SIM卡

-> k2:   重载SIM卡(上命令执行错误，可尝试用这)

-> h:    显示此说明界面
示例：
    【使用功能】${Blue_background_prefix}lpac a${Font_color_suffix}
    【重载SIM卡】${Blue_background_prefix}lpac k${Font_color_suffix}
——————————————————————
${Tip}
①默认只读取SIM1，读取SIM2执行：${Blue_background_prefix}UIM_SLOT=2 lpac${Font_color_suffix}
②因使用LPAC会导致通道占用，引发切换数据无法上网、无法拨打电话、SIM假死等故障。请执行${Blue_background_prefix}[重载SIM卡]${Font_color_suffix}将解除占用
③使用${Blue_background_prefix}[切换eSIM]${Font_color_suffix}并执行${Blue_background_prefix}[重载SIM卡]${Font_color_suffix}若未生效，请重新${Blue_background_prefix}[插拔SIM卡]${Font_color_suffix}即可解决
——————————————————————
  "
}

lpac_menu() {
  lpac_chip_info
  #
  if [[ $ESIM_INIT != "null" ]]; then
  #
  echo -e "
————————————
  ${Green_font_prefix} 1.${Font_color_suffix} 下载 eSIM
  ${Green_font_prefix} 2.${Font_color_suffix} 切换 eSIM
  ${Green_font_prefix} 3.${Font_color_suffix} 删除 eSIM
————————————
  ${Green_font_prefix} 4.${Font_color_suffix} LPA预览
  ${Green_font_prefix} 5.${Font_color_suffix} 设置昵称
  ${Green_font_prefix} 6.${Font_color_suffix} 管理通知
————————————
  ${Green_font_prefix} 7.${Font_color_suffix} 重载 SIM卡
  ${Green_font_prefix} 8.${Font_color_suffix} 重启手机
————————————
  ${Green_font_prefix} 0.${Font_color_suffix} 退出" && echo
#
    echo -e "${Tip_EID}: $ESIM_EID"
    echo -e "${Tip_FREE}: $(($ESIM_FREE / 1024)) KiB"
    if [[ $ESIM_ICCID != "null" ]]; then
      echo -e "${Info_ESIM}: $ESIM_NAME"
      echo -e "${Info_ICCID}: $ESIM_ICCID"
      echo -e "————————————"
    fi
#
  else
    echo -e "$Error eSIM读取失败！请指定SIM卡或${Blue_background_prefix}[插拔SIM卡]${Font_color_suffix}"
    echo -e "$Error 默认读取SIM1，如需读取SIM2请执行："
    echo -e "${Red_background_prefix}UIM_SLOT=2 lpac a${Font_color_suffix}"
    killall com.android.phone && exit
  fi
#
  echo -e "请输入数字选择功能 [0-8]:" && read num
  case "$num" in
  1)
    lpac_profile_download
    ;;
  2)
    lpac_profile_switch
    ;;
  3)
    lpac_profile_delete
    ;;
  4)
    lpac_profile_preview
    ;;
  5)
    lpac_profile_nickname
    ;;
  6)
    lpac_notification
    ;;
  7)
    lpac_kill_info
    ;;
  8)
    lpac_reboot
    ;;
  0)
    killall com.android.phone
    exit
    ;;
  *)
    echo "请输入正确数字 [0-8]"
    ;;
  esac
}

if [[ $UID == "0" || $USER_ID == "0" || `id -u` == "0" ]]; then
  case "$1" in
  a)
    lpac_menu
    ;;
  h)
    lpac_help
    ;;
  k)
    killall com.android.phone
    ;;
  k2)
    am broadcast -a android.intent.action.SIM_STATE_CHANGED
    ;;
  *)
    exec lpac-hw $@
    ;;
  esac
else
  echo -e "${Red_background_prefix}—————— 请使用root权限执行 ——————${Font_color_suffix}"
  exit
fi
