
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __LIBQMI_GLIB_FLAG_TYPES_PRIVATE_H__
#define __LIBQMI_GLIB_FLAG_TYPES_PRIVATE_H__
#include "qmi-enums-private.h"

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "../src/libqmi-glib/qmi-enums-private.h" */
GType qmi_ctl_flag_get_type (void) G_GNUC_CONST;
#define QMI_TYPE_CTL_FLAG (qmi_ctl_flag_get_type ())

/* Define type-specific symbols */
#define __QMI_CTL_FLAG_IS_FLAGS__

gchar *qmi_ctl_flag_build_string_from_mask (QmiCtlFlag mask);
GType qmi_service_flag_get_type (void) G_GNUC_CONST;
#define QMI_TYPE_SERVICE_FLAG (qmi_service_flag_get_type ())

/* Define type-specific symbols */
#define __QMI_SERVICE_FLAG_IS_FLAGS__

gchar *qmi_service_flag_build_string_from_mask (QmiServiceFlag mask);
G_END_DECLS

#endif /* __LIBQMI_GLIB_FLAG_TYPES_PRIVATE_H__ */

/* Generated data ends here */

